--Exercice n° 01

SELECT 
    C.SOCIETE, 
    A.TITRE,
    A.NOM, 
    A.PRENOM
FROM CLIENTS C
JOIN ADRESSES AD ON C.CODE_CLIENT = AD.CODE_CLIENT
JOIN ACHETEURS A ON A.NO_ADRESSE = AD.NO_ADRESSE
JOIN COMMANDES CM ON A.NO_ACHETEUR = CM.NO_ACHETEUR
WHERE AD.PAYS = 'France' 
    AND (A.TITRE = 'Mme' OR A.TITRE = 'Mlle')
    AND EXTRACT(YEAR FROM CM.DATE_COMMANDE) = 2017
    AND EXTRACT(MONTH FROM CM.DATE_COMMANDE) = 5
ORDER BY C.SOCIETE;


--Exercice n° 02

SELECT 
    DISTINCT P.NOM_PRODUIT, 
    P.QUANTITE
FROM PRODUITS P
JOIN DETAILS_COMMANDES DC ON P.REF_PRODUIT = DC.REF_PRODUIT
JOIN COMMANDES C ON DC.NO_COMMANDE = C.NO_COMMANDE
WHERE EXTRACT(YEAR FROM C.DATE_COMMANDE) = 2018
    AND (P.QUANTITE LIKE '%cartons%' OR P.QUANTITE LIKE '%paquets%')
    AND REGEXP_SUBSTR(P.QUANTITE, '[0-9]+') < 300
ORDER BY P.NOM_PRODUIT, P.QUANTITE;


--Exercice n° 03

SELECT 
    A.NOM ||' '|| UPPER(A.PRENOM) AS VENDEUR, 
    EXTRACT(YEAR FROM C.DATE_COMMANDE) AS ANNEE, 
    COUNT(*) AS NB_COMMANDES
FROM ACHETEURS A
JOIN COMMANDES C ON A.NO_ACHETEUR = C.NO_ACHETEUR
JOIN ADRESSES AD ON A.NO_ADRESSE = AD.NO_ADRESSE
WHERE AD.PAYS = 'France' 
    AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = 2019
GROUP BY A.NOM, A.PRENOM, EXTRACT(YEAR FROM C.DATE_COMMANDE)
HAVING COUNT(*) > 20
ORDER BY VENDEUR;


--Exercice n° 04

SELECT 
    DISTINCT AD.VILLE, 
    EXTRACT(YEAR FROM C.DATE_COMMANDE) AS ANNEE, 
    COUNT(DISTINCT C.NO_COMMANDE) AS NB_COMMANDES, 
    SUM(DC.QUANTITE) AS QUANTITES
FROM COMMANDES C
JOIN DETAILS_COMMANDES DC ON C.NO_COMMANDE = DC.NO_COMMANDE
JOIN ACHETEURS A ON C.NO_ACHETEUR = A.NO_ACHETEUR
JOIN ADRESSES AD ON A.NO_ADRESSE = AD.NO_ADRESSE
WHERE EXTRACT(YEAR FROM C.DATE_COMMANDE) = 2019
    AND DC.RETOURNE = 0
GROUP BY AD.VILLE, EXTRACT(YEAR FROM C.DATE_COMMANDE)
HAVING COUNT(DISTINCT C.NO_COMMANDE) > 50;


--Exercice n° 05

SELECT 
    V.PAYS, 
    E.NOM ||' '|| E.PRENOM AS VENDEUR,
    COUNT(C.NO_COMMANDE) AS NB_COMMANDES, 
    SUM(DC.QUANTITE) AS QUANTITES
FROM COMMANDES C
JOIN DETAILS_COMMANDES DC ON C.NO_COMMANDE = DC.NO_COMMANDE
JOIN VENDEURS V ON C.NO_VENDEUR = V.NO_VENDEUR
JOIN EMPLOYES E ON V.NO_VENDEUR = E.NO_EMPLOYE
WHERE C.DATE_COMMANDE = TO_DATE('2019-05-01', 'YYYY-MM-DD')
GROUP BY V.PAYS, E.NOM, E.PRENOM
HAVING SUM(DC.QUANTITE) > 5000;


--Exercice n° 06

SELECT 
    P.NOM_PRODUIT, 
    SUM(DC.QUANTITE) AS TOTAL_QUANTITE, 
    SUM(DC.QUANTITE * DC.PRIX_UNITAIRE) AS VALEUR_TOTALE
FROM PRODUITS P
JOIN DETAILS_COMMANDES DC ON P.REF_PRODUIT = DC.REF_PRODUIT
JOIN COMMANDES C ON DC.NO_COMMANDE = C.NO_COMMANDE
JOIN VENDEURS V ON C.NO_VENDEUR = V.NO_VENDEUR
WHERE P.CODE_CATEGORIE = 6
    AND V.PAYS = 'France'
    AND C.DATE_COMMANDE < TO_DATE('2019-05-01', 'YYYY-MM-DD')
GROUP BY P.NOM_PRODUIT
ORDER BY P.NOM_PRODUIT;


--Exercice n° 07

SELECT 
    V.PAYS, 
    COALESCE(SUM(DC.PORT), 
    0) AS TOTAL_PORT
FROM VENDEURS V
LEFT JOIN COMMANDES C ON V.NO_VENDEUR = C.NO_VENDEUR 
    AND C.DATE_COMMANDE = TO_DATE('2019-05-01', 'YYYY-MM-DD')
LEFT JOIN DETAILS_COMMANDES DC ON C.NO_COMMANDE = DC.NO_COMMANDE
WHERE V.REGION = 'Europe de l''Ouest'
GROUP BY V.PAYS
ORDER BY V.PAYS;


--Exercice n° 08

SELECT 
    CA.NOM_CATEGORIE,
    F.SOCIETE AS FOURNISSEUR, 
    P.NOM_PRODUIT, 
    P.UNITES_STOCK
FROM PRODUITS P
JOIN CATEGORIES CA ON P.CODE_CATEGORIE = CA.CODE_CATEGORIE
JOIN FOURNISSEURS F ON P.NO_FOURNISSEUR = F.NO_FOURNISSEUR
WHERE P.UNITES_STOCK = (
    SELECT MAX(P2.UNITES_STOCK)
    FROM PRODUITS P2
    WHERE P2.CODE_CATEGORIE = P.CODE_CATEGORIE
        AND P2.NO_FOURNISSEUR = P.NO_FOURNISSEUR
)
ORDER BY F.SOCIETE ASC, P.UNITES_STOCK DESC;


--Exercice n° 09

SELECT 
    EXTRACT(YEAR FROM C.DATE_COMMANDE) AS ANNEE,
    EXTRACT(MONTH FROM C.DATE_COMMANDE) AS MOIS,
    SUM(DC.QUANTITE) AS QUANTITES,
    ROUND(
        SUM(DC.PORT) / SUM(SUM(DC.PORT)) OVER (PARTITION BY EXTRACT(YEAR FROM C.DATE_COMMANDE)) * 100, 
        2
    ) AS POURCENTAGE_PORT,
    SUM(SUM(DC.QUANTITE)) OVER (PARTITION BY EXTRACT(YEAR FROM C.DATE_COMMANDE) ORDER BY EXTRACT(MONTH FROM C.DATE_COMMANDE)) AS SOMME_CUMULEE
FROM COMMANDES C
JOIN DETAILS_COMMANDES DC ON C.NO_COMMANDE = DC.NO_COMMANDE
JOIN PRODUITS P ON DC.REF_PRODUIT = P.REF_PRODUIT
JOIN FOURNISSEURS F ON P.NO_FOURNISSEUR = F.NO_FOURNISSEUR
WHERE F.PAYS = 'France'
GROUP BY EXTRACT(YEAR FROM C.DATE_COMMANDE), EXTRACT(MONTH FROM C.DATE_COMMANDE)
ORDER BY ANNEE, MOIS;


--Exercice n° 10

SELECT 
    EXTRACT(YEAR FROM C.DATE_COMMANDE) AS ANNEE,
    E.NOM ||' '|| E.PRENOM AS VENDEUR,
    COUNT(C.NO_COMMANDE) AS NB_COMMANDES,
    SUM(DC.PORT) AS TOTAL_PORT
FROM COMMANDES C
JOIN DETAILS_COMMANDES DC ON C.NO_COMMANDE = DC.NO_COMMANDE
JOIN VENDEURS V ON C.NO_VENDEUR = V.NO_VENDEUR
JOIN EMPLOYES E ON V.NO_VENDEUR = E.NO_EMPLOYE
JOIN PRODUITS P ON DC.REF_PRODUIT = P.REF_PRODUIT
JOIN FOURNISSEURS F ON P.NO_FOURNISSEUR = F.NO_FOURNISSEUR
WHERE V.PAYS = F.PAYS
GROUP BY EXTRACT(YEAR FROM C.DATE_COMMANDE), E.NOM, E.PRENOM
HAVING COUNT(C.NO_COMMANDE) > 600
ORDER BY ANNEE, NB_COMMANDES DESC;