SELECT
NOM_PRODUIT,
SOCIETE FOURNISSEUR,
NOM_CATEGORIE CATEGORIE,
UNITES_STOCK,
QUANTITE
FROM PRODUITS
JOIN FOURNISSEURS USING(NO_FOURNISSEUR)
JOIN CATEGORIES USING(CODE_CATEGORIE)
WHERE (PAYS = 'FRANCE'
OR NOM_CATEGORIE IN ('Boissons','Desserts') )
AND (QUANTITE LIKE '%boîtes%'
OR QUANTITE LIKE '%carton%')
ORDER BY NO_FOURNISSEUR, CODE_CATEGORIE;


SELECT AD.PAYS
,CL.SOCIETE
,AC.NOM||' '||UPPER(AC.PRENOM) VENDEUR
,EXTRACT(YEAR FROM CO.DATE_COMMANDE) ANNEE
,COUNT(DISTINCT CO.NO_COMMANDE) NB_COMMANDES
FROM ADRESSES AD
JOIN ACHETEURS AC ON AC.NO_ADRESSE = AD.NO_ADRESSE
JOIN COMMANDES CO ON CO.NO_ACHETEUR = AC.NO_ACHETEUR
JOIN CLIENTS CL ON AD.CODE_CLIENT = CL.CODE_CLIENT
WHERE EXTRACT(YEAR FROM CO.DATE_COMMANDE) = 2019
GROUP BY AD.PAYS
,CL.SOCIETE
,AC.NOM
, AC.PRENOM
, EXTRACT(YEAR FROM CO.DATE_COMMANDE)
HAVING COUNT(DISTINCT CO.NO_COMMANDE) > 23
ORDER BY AD.PAYS
,CL.SOCIETE
,AC.NOM;

SELECT VN.pays
,EM.NOM||' '||EM.PRENOM VENDEUR
,SUM(DC.PORT) SUM_PORT
FROM EMPLOYES EM
JOIN VENDEURS VN ON VN.NO_VENDEUR = EM.NO_EMPLOYE
JOIN COMMANDES CO ON CO.NO_VENDEUR = VN.NO_VENDEUR
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
WHERE extract(year from CO.DATE_COMMANDE) = 2019
and extract(month from CO.DATE_COMMANDE) = 5
GROUP BY VN.pays
,EM.NOM
,EM.PRENOM
HAVING SUM(DC.PORT) > 80000
ORDER BY VN.pays, EM.NOM;


SELECT A.NOM||' '||A.PRENOM "Employé A",
A.FONCTION,
B.NOM||' '||B.PRENOM "Employé B Gérés par Employé A",
C.NOM||' '||C.PRENOM "Gérés par Employé B"
FROM EMPLOYES A LEFT OUTER JOIN EMPLOYES B
ON ( A.NO_EMPLOYE = B.REND_COMPTE )
LEFT OUTER JOIN EMPLOYES C
ON ( B.NO_EMPLOYE = C.REND_COMPTE )
ORDER BY "Employé A","Employé B Gérés par Employé A","Gérés par Employé B" ;


SELECT VN.PAYS
,FO.SOCIETE
,EM.NOM||' '||UPPER(EM.PRENOM) VENDEUR
,EXTRACT(YEAR FROM CO.DATE_COMMANDE)
,SUM(DC.QUANTITE)
,COUNT(DISTINCT CO.NO_COMMANDE) NB_COMMANDES
FROM EMPLOYES EM
JOIN VENDEURS VN ON VN.NO_VENDEUR = EM.NO_EMPLOYE
JOIN COMMANDES CO ON CO.NO_VENDEUR = VN.NO_VENDEUR
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
JOIN PRODUITS PR ON PR.REF_PRODUIT = DC.REF_PRODUIT
JOIN FOURNISSEURS FO ON FO.NO_FOURNISSEUR = PR.NO_FOURNISSEUR
AND FO.PAYS = VN.PAYS
GROUP BY FO.SOCIETE
,VN.PAYS
,EM.NOM
,EM.PRENOM, EXTRACT(YEAR FROM CO.DATE_COMMANDE)
HAVING COUNT(DISTINCT CO.NO_COMMANDE) > 600
ORDER BY EXTRACT(YEAR FROM CO.DATE_COMMANDE), NB_COMMANDES;


SELECT NOM_CATEGORIE, SOCIETE FOURNISSEUR, NOM_PRODUIT, UNITES_STOCK
FROM PRODUITS PR1
JOIN CATEGORIES CA ON PR1.CODE_CATEGORIE = CA.CODE_CATEGORIE
JOIN FOURNISSEURS FR ON FR.NO_FOURNISSEUR = PR1.NO_FOURNISSEUR
WHERE UNITES_STOCK >(SELECT AVG(PR2.UNITES_STOCK)
FROM PRODUITS PR2
WHERE PR1.NO_FOURNISSEUR = PR2.NO_FOURNISSEUR)
AND NOM_CATEGORIE = 'Desserts'
ORDER BY SOCIETE, UNITES_STOCK DESC;


SELECT FO.PAYS
,CO.ANNEE
,CO.MOIS
,SUM(DC.QUANTITE) QUANTITES
,ROUND(SUM(DC.QUANTITE)*100/
SUM(SUM(DC.QUANTITE)) OVER
(PARTITION BY ANNEE),2) "%"
,SUM(SUM(DC.QUANTITE)) OVER
(PARTITION BY ANNEE ORDER BY MOIS) "Somme cumulative"
FROM COMMANDES CO
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
JOIN PRODUITS PR ON PR.REF_PRODUIT = DC.REF_PRODUIT
JOIN FOURNISSEURS FO ON FO.NO_FOURNISSEUR = PR.NO_FOURNISSEUR
AND FO.PAYS = 'France'
JOIN CATEGORIES CA ON PR.CODE_CATEGORIE = CA.CODE_CATEGORIE
GROUP BY FO.PAYS,ANNEE,MOIS;


