---练习 1

---对于法国供应商，或者类别为“Boissons”（饮料）或“Desserts”（甜点）的产品，显示产品名称、供应商、类别和产品数量。
---显示那些数量以“boîtes”（盒子）或“carton”（纸箱）为单位的产品。

SELECT
    NOM_PRODUIT,
    SOCIETE FOURNISSEUR,
    NOM_CATEGORIE CATEGORIE,
    UNITES_STOCK,
    QUANTITE
FROM PRODUITS
JOIN FOURNISSEURS USING(NO_FOURNISSEUR)
JOIN CATEGORIES USING(CODE_CATEGORIE)
WHERE (PAYS = 'FRANCE'
    OR NOM_CATEGORIE IN ('Boissons', 'Desserts'))
    AND (QUANTITE LIKE '%boîtes%'
    OR QUANTITE LIKE '%carton%')
ORDER BY NO_FOURNISSEUR, CODE_CATEGORIE;


---练习 2

---对于在2019年完成超过23个订单的客户，显示他们所在的国家、公司名称、购买者的姓名和每年订单数量。

SELECT
    AD.PAYS,
    CL.SOCIETE,
    AC.NOM || ' ' || UPPER(AC.PRENOM) VENDEUR,
    EXTRACT(YEAR FROM CO.DATE_COMMANDE) ANNEE,
    COUNT(DISTINCT CO.NO_COMMANDE) NB_COMMANDES
FROM ADRESSES AD
JOIN ACHETEURS AC ON AC.NO_ADRESSE = AD.NO_ADRESSE
JOIN COMMANDES CO ON CO.NO_ACHETEUR = AC.NO_ACHETEUR
JOIN CLIENTS CL ON AD.CODE_CLIENT = CL.CODE_CLIENT
WHERE EXTRACT(YEAR FROM CO.DATE_COMMANDE) = 2019
GROUP BY
    AD.PAYS,
    CL.SOCIETE,
    AC.NOM,
    AC.PRENOM,
    EXTRACT(YEAR FROM CO.DATE_COMMANDE)
HAVING COUNT(DISTINCT CO.NO_COMMANDE) > 23
ORDER BY
    AD.PAYS,
    CL.SOCIETE,
    AC.NOM;


---练习 3

---按销售员和销售员所在国家，计算运费总和。
---仅显示2019年5月且运费总和大于80,000€的记录。

SELECT
    VN.pays,
    EM.NOM || ' ' || EM.PRENOM VENDEUR,
    SUM(DC.PORT) SUM_PORT
FROM EMPLOYES EM
JOIN VENDEURS VN ON VN.NO_VENDEUR = EM.NO_EMPLOYE
JOIN COMMANDES CO ON CO.NO_VENDEUR = VN.NO_VENDEUR
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
WHERE EXTRACT(YEAR FROM CO.DATE_COMMANDE) = 2019
    AND EXTRACT(MONTH FROM CO.DATE_COMMANDE) = 5
GROUP BY
    VN.pays,
    EM.NOM,
    EM.PRENOM
HAVING SUM(DC.PORT) > 80000
ORDER BY VN.pays, EM.NOM;

---练习 4

---显示所有员工的姓名、职位，以及他们管理的员工的姓名，如果有的话，还包括这些员工所管理的员工的姓名。

SELECT
    A.NOM || ' ' || A.PRENOM "Employé A",
    A.FONCTION,
    B.NOM || ' ' || B.PRENOM "Employé B Gérés par Employé A",
    C.NOM || ' ' || C.PRENOM "Gérés par Employé B"
FROM EMPLOYES A
LEFT OUTER JOIN EMPLOYES B ON A.NO_EMPLOYE = B.REND_COMPTE
LEFT OUTER JOIN EMPLOYES C ON B.NO_EMPLOYE = C.REND_COMPTE
ORDER BY "Employé A", "Employé B Gérés par Employé A", "Gérés par Employé B";


---练习 5

---对于与供应商来自同一国家的销售员，显示国家和供应商。
---按年份显示订单数量和销售数量，仅显示订单数量超过600的记录。

SELECT
    VN.PAYS,
    FO.SOCIETE,
    EM.NOM || ' ' || UPPER(EM.PRENOM) VENDEUR,
    EXTRACT(YEAR FROM CO.DATE_COMMANDE),
    SUM(DC.QUANTITE),
    COUNT(DISTINCT CO.NO_COMMANDE) NB_COMMANDES
FROM EMPLOYES EM
JOIN VENDEURS VN ON VN.NO_VENDEUR = EM.NO_EMPLOYE
JOIN COMMANDES CO ON CO.NO_VENDEUR = VN.NO_VENDEUR
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
JOIN PRODUITS PR ON PR.REF_PRODUIT = DC.REF_PRODUIT
JOIN FOURNISSEURS FO ON FO.NO_FOURNISSEUR = PR.NO_FOURNISSEUR
    AND FO.PAYS = VN.PAYS
GROUP BY
    FO.SOCIETE,
    VN.PAYS,
    EM.NOM,
    EM.PRENOM,
    EXTRACT(YEAR FROM CO.DATE_COMMANDE)
HAVING COUNT(DISTINCT CO.NO_COMMANDE) > 600
ORDER BY EXTRACT(YEAR FROM CO.DATE_COMMANDE), NB_COMMANDES;


---练习 6

---对于同一供应商的“Desserts”类别的产品，显示那些库存单位低于该供应商“Desserts”类别产品平均库存的产品的供应商、产品和库存单位。
---按供应商升序和库存单位降序排序。

SELECT
    NOM_CATEGORIE,
    SOCIETE FOURNISSEUR,
    NOM_PRODUIT,
    UNITES_STOCK
FROM PRODUITS PR1
JOIN CATEGORIES CA ON PR1.CODE_CATEGORIE = CA.CODE_CATEGORIE
JOIN FOURNISSEURS FR ON FR.NO_FOURNISSEUR = PR1.NO_FOURNISSEUR
WHERE UNITES_STOCK > (
    SELECT AVG(PR2.UNITES_STOCK)
    FROM PRODUITS PR2
    WHERE PR1.NO_FOURNISSEUR = PR2.NO_FOURNISSEUR
)
AND NOM_CATEGORIE = 'Desserts'
ORDER BY SOCIETE, UNITES_STOCK DESC;


---练习 7

---对于法国的供应商，按年份和月份显示订单数量和销售数量。
---计算运费在年度运费总和中的百分比，以及年度累计销售数量。

SELECT
    FO.PAYS,
    CO.ANNEE,
    CO.MOIS,
    SUM(DC.QUANTITE) QUANTITES,
    ROUND(SUM(DC.QUANTITE) * 100 /
        SUM(SUM(DC.QUANTITE)) OVER (PARTITION BY ANNEE), 2) "%" ,
    SUM(SUM(DC.QUANTITE)) OVER (PARTITION BY ANNEE ORDER BY MOIS) "Somme cumulative"
FROM COMMANDES CO
JOIN DETAILS_COMMANDES DC ON DC.NO_COMMANDE = CO.NO_COMMANDE
JOIN PRODUITS PR ON PR.REF_PRODUIT = DC.REF_PRODUIT
JOIN FOURNISSEURS FO ON FO.NO_FOURNISSEUR = PR.NO_FOURNISSEUR
    AND FO.PAYS = 'France'
JOIN CATEGORIES CA ON PR.CODE_CATEGORIE = CA.CODE_CATEGORIE
GROUP BY FO.PAYS, ANNEE, MOIS;
