SELECT
    societe,
    ville,
    pays
FROM
    fournisseurs;


select 1.56, ceil(1.009), floor(1.99),
       round(1.56),round(1.46),
       round(1.563,2),round(1.465,2),
       round(1563,-2),round(1465,-1),
       trunc(1.56),trunc(1.46)
from 
    dual;


SELECT 
    NOM, 
    PRENOM, 
    FLOOR(SALAIRE / 20) AS Salaire_Journalier_Arrondi
FROM 
    EMPLOYES;

SELECT 
    NOM, 
    PRENOM, 
    CEIL(SALAIRE / 20) AS Salaire_Journalier_Arrondi
FROM 
    EMPLOYES;

SELECT 
    NOM_PRODUIT, 
    UNITES_STOCK, 
    PRIX_UNITAIRE, 
    ROUND(UNITES_STOCK * PRIX_UNITAIRE, -2) AS Valeur_Stock_Arrondie
FROM 
    PRODUITS;

SELECT 
    NOM_PRODUIT, 
    UNITES_STOCK, 
    PRIX_UNITAIRE, 
    FLOOR(UNITES_STOCK * PRIX_UNITAIRE / 10) * 10 AS Valeur_Stock_Arrondie
FROM 
    PRODUITS;

SELECT 
    NOM, 
    PRENOM, 
    ROUND((SALAIRE * 12 + COMMISSION), -2) AS Revenu_Annuel_Arrondi
FROM 
    EMPLOYES;


select sysdate, 
       to_char(sysdate,'d dd ddd mm mon month yyyy'),
       to_char(sysdate+0.5,'hh hh24 mi ss sssss'),
       to_date('01/12/2023','mm/dd/yyyy')
from dual;

select sysdate, 
       to_char(sysdate,'d dd ddd mm mon month yyyy'),
       to_char(sysdate+0.5,'hh hh24 mi ss sssss'),
       to_date('01/12/2023','mm/dd/yyyy')
from dual;

select 
    sysdate+4+31, 
    add_months(sysdate+35,4),
    trunc(months_between(sysdate,date_naissance)),
    last_day(sysdate),
    next_day(sysdate,1)
from employes;


SELECT 
    SUM(UNITES_STOCK * PRIX_UNITAIRE) AS Valeur_Stock,
    SUM(UNITES_COMMANDEES * PRIX_UNITAIRE) AS Valeur_Commande
FROM 
    PRODUITS;

select sum(quantite*prix_unitaire) valeur_produits,
       sum((quantite*prix_unitaire)*(1 - remise/100))  ca
from details_commandes;

SELECT 
    FONCTION, SUM(SALAIRE+NVL(COMMISSION,0)) 
FROM 
    EMPLOYES 
GROUP BY 
    FONCTION; 

SELECT 
    NO_FOURNISSEUR, 
    SUM(PRIX_UNITAIRE*UNITES_STOCK), 
    SUM(PRIX_UNITAIRE*UNITES_COMMANDEES) 
FROM 
    PRODUITS 
WHERE NO_FOURNISSEUR BETWEEN 3 AND 6 
GROUP BY 
    NO_FOURNISSEUR 
HAVING 
    COUNT(DISTINCT CODE_CATEGORIE) >= 3 ; 



SELECT 
    CODE_CLIENT, 
    EXTRACT( YEAR FROM DATE_ENVOI), 
    EXTRACT( MONTH FROM DATE_ENVOI), 
    COUNT(NO_COMMANDE), 
    SUM(PORT) 
FROM 
    COMMANDES 
GROUP BY 
    CODE_CLIENT, 
    EXTRACT( YEAR FROM DATE_ENVOI), 
    EXTRACT( MONTH FROM DATE_ENVOI) 
HAVING 
    COUNT(NO_COMMANDE) > 15 
AND 
    SUM(PORT) > 1400; 


-- 1. 查询为巴黎客户进行销售的员工的名字、姓氏和客户公司

-- ANSI SQL/86

SELECT DISTINCT NOM, PRENOM, SOCIETE 
FROM EMPLOYES A, COMMANDES B, CLIENTS C 
WHERE A.NO_EMPLOYE = B.NO_EMPLOYE 
  AND B.CODE_CLIENT = C.CODE_CLIENT 
  AND C.VILLE = 'Paris';


-- ANSI SQL/92

SELECT 
    NOM, PRENOM, SOCIETE, 
    TO_CHAR(DATE_COMMANDE,'FMDD Month YYYY'), 
    TO_CHAR(PORT,'9G990D00U') 
FROM CLIENTS 
JOIN COMMANDES USING (CODE_CLIENT) 
JOIN EMPLOYES USING (NO_EMPLOYE) 
WHERE VILLE = 'Paris';


-- 2. 查询在2011年5月订购了超过115个产品的客户公司、订购产品的数量、城市和国家

-- ANSI SQL/86

SELECT SOCIETE, COUNT(DISTINCT C.REF_PRODUIT), VILLE, PAYS 
FROM CLIENTS A, COMMANDES B, DETAILS_COMMANDES C 
WHERE A.CODE_CLIENT = B.CODE_CLIENT 
  AND B.NO_COMMANDE = C.NO_COMMANDE 
  AND B.ANNEE = 2011 
  AND B.MOIS = 5 
GROUP BY SOCIETE, VILLE, PAYS 
HAVING COUNT(DISTINCT C.REF_PRODUIT) > 115;


-- ANSI SQL/92

SELECT SOCIETE, COUNT(DISTINCT REF_PRODUIT), VILLE, PAYS 
FROM CLIENTS 
JOIN COMMANDES USING (CODE_CLIENT) 
JOIN DETAILS_COMMANDES USING (NO_COMMANDE) 
WHERE ANNEE = 2011 
  AND MOIS = 5 
GROUP BY SOCIETE, VILLE, PAYS 
HAVING COUNT(DISTINCT REF_PRODUIT) > 115;


-- 3. 查询类别为1、4和7的产品的类别名称、供应商公司和产品名称

-- ANSI SQL/86

SELECT NOM_CATEGORIE, SOCIETE, NOM_PRODUIT 
FROM PRODUITS A, FOURNISSEURS B, CATEGORIES C 
WHERE A.NO_FOURNISSEUR = B.NO_FOURNISSEUR 
  AND A.CODE_CATEGORIE = C.CODE_CATEGORIE 
  AND A.CODE_CATEGORIE IN (1, 4, 7);


-- ANSI SQL/92

SELECT NOM_CATEGORIE, SOCIETE, NOM_PRODUIT 
FROM PRODUITS 
JOIN FOURNISSEURS USING (NO_FOURNISSEUR) 
JOIN CATEGORIES USING (CODE_CATEGORIE) 
WHERE CODE_CATEGORIE IN (1, 4, 7);


-- 4. 查询客户公司、供应商公司及其城市，条件是客户位于供应商所在的城市

-- ANSI SQL/86

SELECT A.SOCIETE, B.SOCIETE, A.VILLE 
FROM FOURNISSEURS A, CLIENTS B 
WHERE A.VILLE = B.VILLE;


-- ANSI SQL/92

SELECT A.SOCIETE, B.SOCIETE, VILLE 
FROM FOURNISSEURS A 
JOIN CLIENTS B USING (VILLE);


-- 5. 查询订购了名为 'Chai' 的产品的客户公司

-- ANSI SQL/86

SELECT SOCIETE, VILLE 
FROM CLIENTS A, COMMANDES B, DETAILS_COMMANDES C, PRODUITS D 
WHERE A.CODE_CLIENT = B.CODE_CLIENT 
  AND B.NO_COMMANDE = C.NO_COMMANDE 
  AND C.REF_PRODUIT = D.REF_PRODUIT 
  AND D.NOM_PRODUIT = 'Chai';


-- ANSI SQL/92

SELECT SOCIETE, VILLE 
FROM CLIENTS 
JOIN COMMANDES USING (CODE_CLIENT) 
JOIN DETAILS_COMMANDES USING (NO_COMMANDE) 
JOIN PRODUITS USING (REF_PRODUIT) 
WHERE NOM_PRODUIT = 'Chai';